---
addons:
  sonarcloud:
    organization:   "$SONAR_ORGANIZATION"
    token:
      secure:       "$SONAR_TOKEN"
    github_token:
      secure:       "$GH_TOKEN"
    branches:
      - master
      - /[build|chore|ci|docs|feat|fix|perf|refactor|revert|spike|style|test].*/
language: java
jdk:
  - oraclejdk8
  - openjdk8
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
